###服务启动端口号
server:
  port: 8200
###服务名称(服务注册到eureka名称)
spring:
  application:
    name: app-weixin
###服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka
swagger:
  base-package: wang.ismy.shopa
  title: 微服务项目-微信服务接口
  version: 1.1
  contact:
    name: MY
    email: 715711877@qq.com